import { UnauthorizedException } from '@nestjs/common';
import { describe, expect, it, jest, beforeEach } from '@jest/globals';
import { AuthService } from './auth.service';
import * as crypto from 'crypto';

describe('AuthService', () => {
  let query: any;
  let service: AuthService;
  const jwtService = { sign: jest.fn(() => 'jwt-token') };

  beforeEach(() => {
    query = {
      select: jest.fn().mockReturnThis(),
      eq: jest.fn().mockReturnThis(),
      single: jest.fn(),
    };

    service = new AuthService(
      { client: { from: jest.fn(() => query) } } as any,
      jwtService as any,
    );
    jwtService.sign.mockClear();
  });

  it('logs in with plain text fallback password', async () => {
    query.single.mockResolvedValue({
      data: {
        id_usuario_sistema: 1,
        username: 'dpilaguano',
        password_hash: 'hash_admin',
        rol_sistema: 'ADMINISTRADOR',
        primer_nombre: 'David',
        primer_apellido: 'Pilaguano',
      },
      error: null,
    });

    const result = await service.login('dpilaguano', 'hash_admin');

    expect(jwtService.sign).toHaveBeenCalledWith(
      expect.objectContaining({
        sub: 1,
        username: 'dpilaguano',
        rol: 'ADMINISTRADOR',
      }),
    );
    expect(result).toEqual({
      access_token: 'jwt-token',
      user: {
        id: 1,
        username: 'dpilaguano',
        rol_sistema: 'ADMINISTRADOR',
        nombre: 'David Pilaguano',
      },
    });
  });

  it('logs in with SHA-256 password generated by user creation', async () => {
    const sha256Password = crypto
      .createHash('sha256')
      .update('123456')
      .digest('hex');

    query.single.mockResolvedValue({
      data: {
        id_usuario_sistema: 2,
        username: 'admin',
        password_hash: sha256Password,
        rol_sistema: 'ADMINISTRADOR',
        primer_nombre: 'Admin',
        primer_apellido: 'Sistema',
      },
      error: null,
    });

    const result = await service.login('admin', '123456');

    expect(result.user).toEqual({
      id: 2,
      username: 'admin',
      rol_sistema: 'ADMINISTRADOR',
      nombre: 'Admin Sistema',
    });
    expect(result.access_token).toBe('jwt-token');
  });

  it('throws when user is missing or inactive', async () => {
    query.single.mockResolvedValue({ data: null, error: { message: 'No row' } });

    await expect(service.login('missing', '123')).rejects.toThrow(
      UnauthorizedException,
    );
  });

  it('throws when password is invalid', async () => {
    query.single.mockResolvedValue({
      data: {
        id_usuario_sistema: 1,
        username: 'dpilaguano',
        password_hash: 'hash_admin',
        rol_sistema: 'ADMINISTRADOR',
        primer_nombre: 'David',
        primer_apellido: 'Pilaguano',
      },
      error: null,
    });

    await expect(service.login('dpilaguano', 'bad')).rejects.toThrow(
      UnauthorizedException,
    );
  });
});
